name: Publish Docker image

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Steam branch'
        required: true
        default: 'public'

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: Liassid
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            BRANCH=${{ github.event.inputs.branch }}
          tags: |
            ghcr.io/liassid/scpsl-image:${{ github.event.inputs.branch }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
